apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: backstage-portal
  title: My Hackstage 
  description: Personal developer portal for managing vibecoding projects.
  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: website
  owner: guests
  lifecycle: experimental
